In [2]:
import pandas as pd
import numpy as np
import re, codecs

In [44]:
def only_arabic(code_data):
    text = code_data.text.tolist()
    label = code_data.label.tolist()
    sentences = []
    for line in range(len(text)):
        stripped = str(" ".join(re.findall(r'[\u0600-\u06FF]+', text[line])))
        stripped = re.sub('_', '', stripped)
        stripped = re.sub('\s+', ' ', stripped)
        if(stripped != ''):
            sentences.append([str(stripped).lower(), int(label[line])])
    return pd.DataFrame(sentences, columns = ['text', 'label'])

In [45]:
df = pd.read_csv('Corpus/big_corpus.csv')
df

                                                    text  label
0      Лива Туввар Сирия АлЛажатта # IslamState-қа қа...      1
1       террористік иттер бүлікшілерге айналады! #Tur...      1
2      Әл-Хайрдың Газваты 13 арнайы аймақ. Олардан ке...      1
3      Сирия-дағы # Ресей | n 'басып кіру' туралы ала...      1
4      Ядролық соғыс соғысы келе жатыр !!! <a href="h...      1
...                                                  ...    ...
49523             Жақсы өмір сүруге тыйым сала алмайсын😃      2
49524                91 дің концертіне жиналған иглздар😆      2
49525  Панданың қалай пайда болғанын енді түсіндім......      2
49526  Мүбәрәк болсын Жұмаңыз☝, Қабыл болсын дұғаңыз🙏...      2
49527               Кез келген Қасқырыңды шақыр айрамын😄      2

[49528 rows x 2 columns]

In [60]:
df['count'] = df['text'].str.count(' ') + 1
count = df.loc[(df['label'] == 0) | (df['label'] == 1)]['count'].sum()
print(count)
print(df['count'].sum())

1515010
1897143

In [61]:
only = only_arabic(df)
only

                                                  text  label
0                                      إمارة الإسلامية      1
1                                      إمارة الإسلامية      1
2    ثانيه من الممكن استعمالها واظن انها افضل من طر...      1
3    قل هل تربصون بنآ الآ احدى الحسنيين ونحن نتربص ...      1
4    نازلة من النوازل هُوَ سَمَّاكُمُ الْمُسْلِمينَ...      1
..                                                 ...    ...
917   اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2
918   اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2
919   اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2
920                                                  ٶ      2
921                                 صلى الله عليه وسلم      2

[922 rows x 2 columns]

In [62]:
only['count'] = only['text'].str.count(' ') + 1
only

                                                  text  label  count
0                                      إمارة الإسلامية      1      2
1                                      إمارة الإسلامية      1      2
2    ثانيه من الممكن استعمالها واظن انها افضل من طر...      1     15
3    قل هل تربصون بنآ الآ احدى الحسنيين ونحن نتربص ...      1     41
4    نازلة من النوازل هُوَ سَمَّاكُمُ الْمُسْلِمينَ...      1    139
..                                                 ...    ...    ...
917   اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2      9
918   اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2      9
919   اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2      9
920                                                  ٶ      2      1
921                                 صلى الله عليه وسلم      2      4

[922 rows x 3 columns]

In [63]:
only.loc[(only['label'] == 2)]

                                                 text  label  count
917  اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2      9
918  اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2      9
919  اللهم إني أصلي لك، والحفاظ على الناس الذين أحبهم      2      9
920                                                 ٶ      2      1
921                                صلى الله عليه وسلم      2      4

In [64]:
count_arabic = only.loc[(only['label'] == 0) | (only['label'] == 1)]['count'].sum()
count_arabic

18441

In [68]:
print((count_arabic/count)*100, 'percent')

1.217219688318889 percent